### ISSUE TITLE
Crash on slack message before bot joined irc.

### ISSUE THREAD

**Issue by Slind14** [fntsrlike/slack-irc-plugin#18]
If a message is being sent from slack before the bot fully connected to the irc network it crashes:

```
/home/irc-relay/slack-irc-syncbot/node_modules/irc/lib/irc.js:929
    if (c.match(/\s/)) {
          ^
TypeError: Cannot call method 'match' of undefined
    at Client._splitLongLines (/home/irc-relay/slack-irc-syncbot/node_modules/irc/lib/irc.js:929:11)
    at /home/irc-relay/slack-irc-syncbot/node_modules/irc/lib/irc.js:965:36
    at Array.forEach (native)
    at Client._speak (/home/irc-relay/slack-irc-syncbot/node_modules/irc/lib/irc.js:964:12)
    at Client.say (/home/irc-relay/slack-irc-syncbot/node_modules/irc/lib/irc.js:951:10)
    at IrcBot.speak (/home/irc-relay/slack-irc-syncbot/lib/ircbot.js:127:17)
    at SlackToIRC._sentMessage (/home/irc-relay/slack-irc-syncbot/lib/slack-to-irc.js:72:15)
    at null.<anonymous> (/home/irc-relay/slack-irc-syncbot/lib/slack-to-irc.js:53:12)
    at IncomingMessage.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (_stream_readable.js:746:14)
```

**Comment by fntsrlike** [comment]
Reference: https://github.com/martynsmith/node-irc/issues/326
